### ISSUE TITLE
live demo 404?

### ISSUE THREAD

**Issue by 1c7** [brandonasuncion/Pixel#2]
![image](https://user-images.githubusercontent.com/1804755/48049258-08683500-e1d9-11e8-8f6f-4f397aaee8bb.png)

**Comment by 1c7** [comment]
I click "Deploy to Heroku" and get it working
https://c17-pixel.herokuapp.com

![image](https://user-images.githubusercontent.com/1804755/48049795-c7712000-e1da-11e8-9ca7-cb57d58571d6.png)

Thanks for the demo

**Comment by 1c7** [comment]
seem like it work on Mobile (Android 7.0 + Chrome 70.0.3538.80) (Samsung Galaxy Note5)(2015 Phone)
![image](https://user-images.githubusercontent.com/1804755/48049874-08693480-e1db-11e8-8ae6-1bc367da153c.png)

**Comment by 1c7** [comment]
I can't click 1-9 and place color, but basic display & zoom seem work

**Comment by 1c7** [comment]
Thanks again

**Comment by brandonasuncion** [comment]
I don't seem to be getting any 404 errors on the demo link.
But the code is primarily tested to work in Google Chrome for Desktop. Feel free to fork the project and make modifications. :)
